# Generated by Django 4.1 on 2022-10-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_contact_mobilenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
