# Generated by Django 4.1 on 2022-10-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_contact_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobilenumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
